# Generated by Django 4.1.7 on 2023-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30, verbose_name='Blog titel')),
                ('img', models.ImageField(upload_to='media/blog', verbose_name='Blog image')),
                ('descr', models.CharField(max_length=20, verbose_name='Blog description')),
                ('date', models.DateField(verbose_name='Blog release time')),
                ('time', models.TimeField(verbose_name='Blog reading time')),
                ('slug', models.SlugField(unique=True, verbose_name='Blog link')),
                ('active', models.BooleanField(verbose_name='Blog active')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='HomeMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='media', verbose_name='HomeMain background image1')),
                ('img2', models.ImageField(upload_to='media', verbose_name='HomeMain background image2')),
                ('img3', models.ImageField(upload_to='media', verbose_name='HomeMain background image3')),
            ],
        ),
        migrations.CreateModel(
            name='HomeMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30, verbose_name='HomeMotivation titel')),
                ('img', models.ImageField(upload_to='media/png', verbose_name='HomeMotivation image')),
                ('descr', models.CharField(max_length=200, verbose_name='HomeMotivation description')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30, verbose_name='Project titel')),
                ('img', models.ImageField(upload_to='media/porfolio', verbose_name='Project image')),
                ('descr', models.CharField(max_length=20, verbose_name='Project description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Project link')),
                ('active', models.BooleanField(verbose_name='Project active')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30, verbose_name='Service titel')),
                ('img', models.ImageField(upload_to='media/service', verbose_name='Service image')),
                ('descr', models.CharField(max_length=20, verbose_name='Service description')),
                ('slug', models.SlugField(unique=True, verbose_name='Service link')),
            ],
        ),
    ]
