# Generated by Django 4.1.7 on 2023-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_homemain_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemotivation',
            name='img',
        ),
        migrations.AddField(
            model_name='homemotivation',
            name='icon',
            field=models.CharField(default=1, max_length=30, verbose_name='HomeMotivation icon'),
            preserve_default=False,
        ),
    ]
