# Generated by Django 4.1.7 on 2023-03-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_homemotivation_img_homemotivation_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background',
        ),
        migrations.AlterField(
            model_name='project',
            name='descr',
            field=models.CharField(max_length=55, verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='descr',
            field=models.CharField(max_length=300, verbose_name='Service description'),
        ),
    ]
