# Generated by Django 4.1.7 on 2023-03-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blog_descr_alter_blog_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='My',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/my', verbose_name='My img')),
                ('titel', models.CharField(max_length=30, verbose_name='Blog titel')),
                ('descr', models.CharField(max_length=1500, verbose_name='Blog description')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='showline',
            field=models.CharField(default=1, max_length=300, verbose_name='Blog showline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='descr',
            field=models.CharField(max_length=2000, verbose_name='Blog descr'),
        ),
    ]
