# Generated by Django 4.1.7 on 2023-03-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_my_blog_showline_alter_blog_descr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my',
            options={'verbose_name': 'My', 'verbose_name_plural': 'My'},
        ),
    ]
