# Generated by Django 4.1.7 on 2023-03-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_my_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descr',
            field=models.TextField(max_length=2000, verbose_name='Blog descr'),
        ),
        migrations.AlterField(
            model_name='my',
            name='descr',
            field=models.TextField(max_length=1500, verbose_name='Blog description'),
        ),
    ]
