# Generated by Django 4.1.7 on 2023-03-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_blog_descr_alter_my_descr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='showline',
        ),
        migrations.AlterField(
            model_name='blog',
            name='descr',
            field=models.CharField(max_length=300, verbose_name='Blog description'),
        ),
    ]
