# Generated by Django 4.1.7 on 2023-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_blog_showline_alter_blog_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='titel',
            field=models.CharField(max_length=60, verbose_name='Blog titel'),
        ),
    ]
