# Generated by Django 4.1.7 on 2023-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_titel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30, verbose_name='Services titel')),
                ('img_main', models.ImageField(upload_to='media/service', verbose_name='Services image')),
                ('descr', models.CharField(max_length=300, verbose_name='Services description')),
                ('slug', models.SlugField(unique=True, verbose_name='Services link')),
                ('text', models.TextField(blank=True, verbose_name='Services text')),
                ('img_1', models.ImageField(blank=True, upload_to='media/service', verbose_name='Services image1')),
                ('img_2', models.ImageField(blank=True, upload_to='media/service', verbose_name='Services image2')),
                ('img_3', models.ImageField(blank=True, upload_to='media/service', verbose_name='Services image3')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
