# Generated by Django 4.1.7 on 2023-04-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_services_delete_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='text',
        ),
        migrations.AddField(
            model_name='services',
            name='text1',
            field=models.TextField(blank=True, verbose_name='Services text1'),
        ),
        migrations.AddField(
            model_name='services',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Services text2'),
        ),
        migrations.AddField(
            model_name='services',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Services text3'),
        ),
        migrations.AddField(
            model_name='services',
            name='text4',
            field=models.TextField(blank=True, verbose_name='Services text4'),
        ),
        migrations.AddField(
            model_name='services',
            name='text5',
            field=models.TextField(blank=True, verbose_name='Services text5'),
        ),
        migrations.AddField(
            model_name='services',
            name='text6',
            field=models.TextField(blank=True, verbose_name='Services text6'),
        ),
    ]
