# Generated by Django 4.1.7 on 2023-04-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_services_options_remove_services_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ServiseDetails name')),
                ('service_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiseDetails', to='main.services')),
            ],
            options={
                'verbose_name': 'ServiseDetails',
                'verbose_name_plural': 'ServiceDetails',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Article name')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='main.blog')),
            ],
        ),
    ]
