# Generated by Django 4.1.7 on 2023-04-01 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_servisedetails_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_main', models.ImageField(upload_to='media/service', verbose_name='ServicesMain image')),
                ('descr', models.CharField(max_length=300, verbose_name='ServicesMain description')),
                ('name', models.CharField(max_length=30, verbose_name='ServiseMain name')),
            ],
            options={
                'verbose_name': 'ServiseMain',
                'verbose_name_plural': 'ServiceMain',
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='services',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='services',
            name='img_main',
        ),
        migrations.AddField(
            model_name='article',
            name='img1',
            field=models.ImageField(blank=True, upload_to='media/article', verbose_name='Aticle image'),
        ),
        migrations.AddField(
            model_name='article',
            name='img2',
            field=models.ImageField(blank=True, upload_to='media/article', verbose_name='Article image'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Article tlink'),
        ),
        migrations.AddField(
            model_name='article',
            name='text1',
            field=models.TextField(blank=True, verbose_name='Article text1'),
        ),
        migrations.AddField(
            model_name='article',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Article text2'),
        ),
        migrations.AddField(
            model_name='article',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Article text3'),
        ),
        migrations.AddField(
            model_name='article',
            name='text4',
            field=models.TextField(blank=True, verbose_name='Article text4'),
        ),
        migrations.AddField(
            model_name='article',
            name='text5',
            field=models.TextField(blank=True, verbose_name='Article text5'),
        ),
        migrations.AddField(
            model_name='article',
            name='text6',
            field=models.TextField(blank=True, verbose_name='Article text6'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='main.blog'),
        ),
        migrations.DeleteModel(
            name='ServiseDetails',
        ),
        migrations.AddField(
            model_name='services',
            name='service_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.servicesmain'),
            preserve_default=False,
        ),
    ]
