# Generated by Django 4.1.7 on 2023-04-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_article_slug_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_main', models.ImageField(upload_to='media/service', verbose_name='ServicessAll image')),
                ('descr', models.CharField(max_length=300, verbose_name='ServicessAll description')),
                ('name', models.CharField(max_length=30, verbose_name='ServisesAll name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='ServicesAll link')),
            ],
            options={
                'verbose_name': 'ServiseMain',
                'verbose_name_plural': 'ServiceMain',
            },
        ),
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='main.servicesall'),
        ),
        migrations.DeleteModel(
            name='ServicesMain',
        ),
    ]
