# Generated by Django 4.1.7 on 2023-04-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_services_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesall',
            name='slug',
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Services link'),
        ),
    ]
