# Generated by Django 4.1.7 on 2023-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_servicesall_slug_services_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
        migrations.AddField(
            model_name='servicesall',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='ServicesAll link'),
        ),
    ]
