# Generated by Django 4.1.7 on 2023-04-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_services_slug_servicesall_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('img_main', models.ImageField(blank=True, upload_to='media/category', verbose_name='Category image')),
                ('descr', models.TextField(max_length=1500, verbose_name='Caregory description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Category link')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='SubCategory link')),
                ('active', models.BooleanField(blank=True, verbose_name='Blog active')),
                ('titel', models.CharField(max_length=30, verbose_name='SubCategory titel')),
                ('text1', models.TextField(blank=True, verbose_name='SubCategory text1')),
                ('text2', models.TextField(blank=True, verbose_name='SubCategory text2')),
                ('text3', models.TextField(blank=True, verbose_name='SubCategory text3')),
                ('text4', models.TextField(blank=True, verbose_name='SubCategory text4')),
                ('text5', models.TextField(blank=True, verbose_name='SubCategory text5')),
                ('text6', models.TextField(blank=True, verbose_name='SubCategory text6')),
                ('img_1', models.ImageField(blank=True, upload_to='media/sub_category', verbose_name='SubCategory image1')),
                ('img_2', models.ImageField(blank=True, upload_to='media/sub_category', verbose_name='SubCategory image2')),
                ('img_3', models.ImageField(blank=True, upload_to='media/sub_category', verbose_name='SubCategory image3')),
                ('date', models.DateField(blank=True, verbose_name='Blog release time')),
                ('time', models.CharField(blank=True, max_length=2, verbose_name='Blog reading time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categ', to='main.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategory',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='My',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='ServicesAll',
        ),
    ]
