# Generated by Django 4.1.7 on 2023-04-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_category_subcategory_delete_blog_delete_my_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img_main',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='descr',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Caregory description'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='img_main',
            field=models.ImageField(blank=True, upload_to='media/category', verbose_name='Category image'),
        ),
    ]
