# Generated by Django 4.1.7 on 2023-04-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_blogcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Article link'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Article link'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Article link'),
        ),
    ]
